spring.application.name=medcare

# MySQL Database (localhost)
spring.datasource.url=jdbc:mysql://localhost:3306/medcare_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=Bhuvanesh
spring.datasource.password=Bhuvi@2006

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
